language: go

gobuild_args: -v -race
go:
  - 1.20.x

service:
  - docker

git:
  depth: 1

env:
  global:
    - USER="okpalaChidiebere"
    - DOCKER_USERNAME="aluminetchidiebre"
    - SERVICE_NAME="chirper-app-image-filter-service"
    - GOPRIVATE="github.com/${USER}"
    - DOCKER_BUILDKIT=1
    - EXECUTION_ENVIRONMENT="test"

# Pre-testing installs
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > $HOME/.netrc
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2

install:
  - echo "no additional dependencies needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "skipping before_script step..."

script:
  - golangci-lint run --disable errcheck

after_success:
  - docker --version
  # we will not build the new image unless the test and lints scripts are successful
  - docker build --secret id=gitcredentials,src=$HOME/.netrc -t "$DOCKER_USERNAME"/"$SERVICE_NAME":"$TRAVIS_BUILD_ID" --build-arg GOPRIVATE=$GOPRIVATE .

before_deploy:
  #  the deploy phase will only run if we successfully login into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker images;
    docker push "$DOCKER_USERNAME"/"$SERVICE_NAME":"$TRAVIS_BUILD_ID";
