// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package imagefilteraccess is a generated GoMock package.
package imagefilteraccess

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPresignerRepository is a mock of PresignerRepository interface.
type MockPresignerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPresignerRepositoryMockRecorder
}

// MockPresignerRepositoryMockRecorder is the mock recorder for MockPresignerRepository.
type MockPresignerRepositoryMockRecorder struct {
	mock *MockPresignerRepository
}

// NewMockPresignerRepository creates a new mock instance.
func NewMockPresignerRepository(ctrl *gomock.Controller) *MockPresignerRepository {
	mock := &MockPresignerRepository{ctrl: ctrl}
	mock.recorder = &MockPresignerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresignerRepository) EXPECT() *MockPresignerRepositoryMockRecorder {
	return m.recorder
}

// GetGetSignedUrl mocks base method.
func (m *MockPresignerRepository) GetGetSignedUrl(ctx context.Context, bucketName, objectKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGetSignedUrl", ctx, bucketName, objectKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGetSignedUrl indicates an expected call of GetGetSignedUrl.
func (mr *MockPresignerRepositoryMockRecorder) GetGetSignedUrl(ctx, bucketName, objectKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGetSignedUrl", reflect.TypeOf((*MockPresignerRepository)(nil).GetGetSignedUrl), ctx, bucketName, objectKey)
}

// GetPutSignedUrl mocks base method.
func (m *MockPresignerRepository) GetPutSignedUrl(ctx context.Context, bucketName, objectKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPutSignedUrl", ctx, bucketName, objectKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPutSignedUrl indicates an expected call of GetPutSignedUrl.
func (mr *MockPresignerRepositoryMockRecorder) GetPutSignedUrl(ctx, bucketName, objectKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPutSignedUrl", reflect.TypeOf((*MockPresignerRepository)(nil).GetPutSignedUrl), ctx, bucketName, objectKey)
}
